# Generated by Django 4.0.2 on 2022-03-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infplace', models.CharField(max_length=100, verbose_name='المكان')),
                ('infphone_number', models.CharField(max_length=20, verbose_name='الموبيل')),
                ('infemail', models.EmailField(max_length=200)),
            ],
        ),
    ]
