# Generated by Django 4.0.2 on 2022-02-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIimage', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='صوره المنتج')),
                ('PRDIprodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='المنتج')),
            ],
        ),
    ]
