# Generated by Django 4.0.2 on 2022-02-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='PRDIimage',
            field=models.ImageField(upload_to='product_photo/%Y/%m/%d/', verbose_name='صوره المنتج'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATname', models.CharField(max_length=100, verbose_name=' اسم التصنيف')),
                ('CATdesc', models.TextField(verbose_name='وصف التصنيف')),
                ('CATimage', models.ImageField(upload_to='category/%Y/%m/%d/', verbose_name='صوره التصنيف')),
                ('CATparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name=' التصنيف الرئيسي')),
            ],
        ),
    ]
