# Generated by Django 4.0.2 on 2022-02-25 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_image_prdiimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name=' التصنيف الرئيسي'),
        ),
        migrations.CreateModel(
            name='Product_alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNalternatives', models.ManyToManyField(related_name='alternative_product', to='product.Product', verbose_name=' اسم البدائل')),
                ('PALNproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name=' اسم المنتج')),
            ],
        ),
    ]
