# Generated by Django 4.0.2 on 2022-02-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_catparent_product_alternative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Imagies'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product_alternative', 'verbose_name_plural': 'Product_alternativeies'},
        ),
        migrations.CreateModel(
            name='Product_accessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCalternatives', models.ManyToManyField(related_name='accessory_product', to='product.Product', verbose_name=' اسم البدائل')),
                ('PACCproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_accessory', to='product.product', verbose_name=' اسم المنتج')),
            ],
            options={
                'verbose_name': 'Product_accessor',
                'verbose_name_plural': 'Product_accessories',
            },
        ),
    ]
