# Generated by Django 4.0.2 on 2022-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRNname', models.CharField(max_length=100, verbose_name=' اسم البراند')),
                ('BRNdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='  وصف البراند')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VARname', models.CharField(max_length=100, verbose_name=' اسم البديل')),
                ('VARdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='  وصف البديل')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
    ]
