# Generated by Django 4.0.2 on 2022-02-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDimage',
            field=models.ImageField(default=1, upload_to='product_photo/%Y/%m/%d/', verbose_name='الصوره الرئيسية للمنتج'),
            preserve_default=False,
        ),
    ]
