# Generated by Django 4.0.2 on 2022-02-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='الخصم '),
            preserve_default=False,
        ),
    ]
