# Generated by Django 4.0.2 on 2022-02-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_prddiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDdiscountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='الخصم '),
        ),
    ]
