# Generated by Django 4.0.2 on 2022-02-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_prddiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDisbeatsaller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDisnew',
            field=models.BooleanField(default=True),
        ),
    ]
