# Generated by Django 4.0.2 on 2022-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_prdisbeatsaller_product_prdisnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDreview',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
