# Generated by Django 4.0.2 on 2022-02-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_prdreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDreview',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=6, null=True),
        ),
    ]
