# Generated by Django 4.0.2 on 2022-02-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_prdreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDreview',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
