# Generated by Django 4.0.2 on 2022-02-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_prdquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDquantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكميه فى المخزن '),
        ),
    ]
