# Generated by Django 4.0.2 on 2022-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_prdquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDisdiscount',
            field=models.BooleanField(default=False, verbose_name='خصومات  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDisbeatsaller',
            field=models.BooleanField(default=False, verbose_name='  منتج الاكثر مبيعا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDisnew',
            field=models.BooleanField(default=False, verbose_name='منتج مضاف حديثا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDreview',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='معدل التقيم'),
        ),
    ]
