# Generated by Django 4.0.2 on 2022-03-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_prdisdiscount_alter_product_prdisbeatsaller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='شحن مجانى  '),
        ),
    ]
