# Generated by Django 4.0.2 on 2022-03-12 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_product_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='المنتج')),
            ],
        ),
    ]
