# Generated by Django 4.0.2 on 2022-03-01 01:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d/', verbose_name='الصوره الرئيسية للعميل')),
                ('join_date', models.DateTimeField(default=datetime.datetime.now)),
                ('phone_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
