# Generated by Django 4.0.2 on 2022-03-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('Street_name', models.TextField(blank=True, null=True)),
                ('Building_name_or_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Region', models.TextField()),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('Governorate', models.TextField()),
                ('nearest_mark', models.TextField(blank=True, null=True)),
                ('is_home', models.BooleanField(blank=True, default=False, null=True)),
                ('is_work', models.BooleanField(blank=True, default=False, null=True)),
                ('is_friday', models.BooleanField(blank=True, default=False, null=True)),
                ('is_starday', models.BooleanField(blank=True, default=False, null=True)),
                ('is_main_address', models.BooleanField(blank=True, default=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
