# Generated by Django 4.0.2 on 2022-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Building_name_or_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Governorate',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='Region',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='nearest_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
