# Generated by Django 4.0.2 on 2022-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_building_name_or_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_friday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_main_address',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_starday',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_work',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
