# Generated by Django 4.0.2 on 2022-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
