# Generated by Django 4.0.2 on 2022-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_showin_cart',
            field=models.BooleanField(default=True, verbose_name='الظهور فى العربة'),
        ),
    ]
