# Generated by Django 4.0.2 on 2022-03-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderdetails_is_showin_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name=' مجمل الاورد'),
        ),
    ]
